# Run with docker-compose up

version: "1.3"

services:
  app:
    build: 
      dockerfile: Dockerfile
      context: ./app
    volumes:
      - ./app:/usr/app
    restart: always

  nginx:
    build: 
      dockerfile: Dockerfile
      context: ./nginx
    ports:
      - "5000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app
    restart: always
